const PROFILE_KEYS=['email','startDate','endDate','resigned','documents']
export function employeeProfile(emp){return {email:emp.email||'',startDate:emp.startDate||'',endDate:emp.endDate||'',resigned:!!emp.resigned,documents:emp.documents||[]}}
export function decodeEmployee(emp){return {...emp,...employeeProfile({...emp,...emp.salary?.employeeProfile})}}
export function encodeEmployee(emp){const row={...emp,salary:{...emp.salary,employeeProfile:employeeProfile(emp)}};for(const key of PROFILE_KEYS)delete row[key];return row}
export function validateEmployment(emp){if(emp.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emp.email))return 'Email chưa đúng định dạng.';if(emp.startDate&&emp.endDate&&emp.endDate<emp.startDate)return 'Ngày nghỉ làm không thể trước ngày vào làm.';return ''}
export function employeeGroup(employees,resigned){return employees.filter(e=>!!e.resigned===resigned)}
function openDocuments(){return new Promise((resolve,reject)=>{const request=indexedDB.open('payslip_employee_documents_v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('files',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function storeDocument(file,kind,client,employeeId){const doc={id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type,kind,addedAt:new Date().toISOString()};if(client){const {data:{session}}=await client.auth.getSession();if(!session)throw new Error('Vui lòng đăng nhập để tải hồ sơ dùng chung.');const path=employeeId+'/'+doc.id;const {error}=await client.storage.from('employee-documents').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw new Error('Kho hồ sơ chưa sẵn sàng hoặc bạn chưa có quyền: '+error.message);return {...doc,storage:'supabase',path}}const db=await openDocuments();try{await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put({...doc,blob:file});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}return doc}
export async function readDocument(doc,client){if(doc.storage==='supabase'){if(!client)throw new Error('Cần kết nối Supabase để tải hồ sơ này.');const {data,error}=await client.storage.from('employee-documents').download(doc.path);if(error)throw new Error('Không tải được hồ sơ dùng chung. Hãy kiểm tra đăng nhập và quyền truy cập.');return data}const id=typeof doc==='string'?doc:doc.id;const db=await openDocuments();try{return await new Promise((resolve,reject)=>{const req=db.transaction('files').objectStore('files').get(id);req.onsuccess=()=>resolve(req.result?.blob);req.onerror=()=>reject(req.error)})}finally{db.close()}}
