import {useEffect,useLayoutEffect,useRef,useState} from 'react'

// Save only changed IDs, so one browser cannot erase rows added by another.
export class SharedCollection {
 constructor(client,table,key=null){this.key=key;this.client=client;this.table=table;this.shown=new Map();this.pending=new Map(key?JSON.parse(localStorage.getItem(key)||'[]'):[]);this.chain=Promise.resolve();this.retryAfter=0;this.failures=0;this.revision=0}
 persist(){if(this.key)localStorage.setItem(this.key,JSON.stringify([...this.pending]))}
 accept(rows){this.shown=new Map(rows.map(row=>[row.id,JSON.stringify(row)]));return rows}
 edit(rows){this.revision++;const next=new Map(rows.map(row=>[row.id,JSON.stringify(row)]));for(const [id,json] of next)if(this.shown.get(id)!==json)this.pending.set(id,JSON.parse(json));for(const id of this.shown.keys())if(!next.has(id))this.pending.set(id,null);this.shown=next;this.persist()}
 flush(force=false){if(this.inFlight)return this.inFlight;if(!force&&Date.now()<this.retryAfter)return Promise.reject(this.lastError);const operation=async()=>{while(this.pending.size){const entries=[...this.pending].slice(0,50),writes=entries.filter(([,row])=>row!==null),deletes=entries.filter(([,row])=>row===null);if(writes.length){const {error}=await this.client.from(this.table).upsert(writes.map(([id,row])=>({id,data:row})));if(error)throw error;for(const [id,row] of writes)if(this.pending.get(id)===row)this.pending.delete(id);this.persist()}if(deletes.length){const {error}=await this.client.from(this.table).delete().in('id',deletes.map(([id])=>id));if(error)throw error;for(const [id,row] of deletes)if(this.pending.has(id)&&this.pending.get(id)===row)this.pending.delete(id);this.persist()}}};this.inFlight=operation().then(()=>{this.failures=0;this.retryAfter=0;this.lastError=null}).catch(error=>{this.lastError=error;this.failures++;this.retryAfter=Date.now()+Math.min(300000,15000*2**Math.min(this.failures,5));throw error}).finally(()=>{this.inFlight=null});return this.inFlight}
 async load(){const revision=this.revision;const rows=[];for(let from=0;;from+=500){const {data,error}=await this.client.from(this.table).select('id,data').order('id').range(from,from+499);if(error)throw error;rows.push(...data.map(row=>({...row.data,id:row.id})));if(data.length<500)break}const merged=new Map(rows.map(row=>[row.id,row]));for(const [id,row] of this.pending){if(row)merged.set(id,row);else merged.delete(id)}const result=[...merged.values()];return this.revision===revision?this.accept(result):result}
 async importMissing(rows){const remote=await this.load(),known=new Set(remote.map(row=>row.id));for(const row of rows)if(!known.has(row.id))this.pending.set(row.id,row);this.persist();await this.flush(true);return this.load()}
}
export function useSharedPayroll(client,user,attendance,payslips,setAttendance,setPayslips,setError){
 const refreshRef=useRef(null),[connectionError,setConnectionError]=useState(''),stores=useRef(null),[ready,setReady]=useState(false),[saving,setSaving]=useState(false)
 useEffect(()=>{if(!client||!user){stores.current=null;setReady(false);if(client){setAttendance([]);setPayslips([])}return}let disposed=false,running=false,lastReported='';const a=new SharedCollection(client,'payroll_attendance','payroll_pending_att_'+user.id),p=new SharedCollection(client,'payroll_payslips','payroll_pending_ps_'+user.id);stores.current={a,p};setReady(false);setConnectionError('')
 const refresh=async(force=false)=>{if(running||disposed)return;running=true;try{let saveError;try{await Promise.all([a.flush(force===true),p.flush(force===true)])}catch(error){saveError=error}const av=a.revision,pv=p.revision;const [ar,pr]=await Promise.all([a.load(),p.load()]);if(!disposed){if(a.revision===av)setAttendance(ar);if(p.revision===pv)setPayslips(pr);setReady(true);setConnectionError('');if(saveError){if(lastReported!==saveError.message)setError('Chưa lưu lên dữ liệu dùng chung: '+saveError.message+' Dữ liệu chưa gửi được vẫn giữ trên máy và sẽ tự thử lại.');lastReported=saveError.message}else lastReported='' }}catch(error){if(!disposed){setConnectionError(error.message);if(lastReported!==error.message)setError('Chưa đồng bộ dữ liệu dùng chung: '+error.message);lastReported=error.message}}finally{running=false}}
 refreshRef.current=refresh;refresh();const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{disposed=true;clearInterval(timer);window.removeEventListener('focus',refresh);if(stores.current?.a===a)stores.current=null}
 },[client,user?.id])
 useLayoutEffect(()=>{if(!ready||!stores.current)return;const {a,p}=stores.current;a.edit(attendance);p.edit(payslips);let active=true;setSaving(true);Promise.all([a.flush(),p.flush()]).catch(error=>{if(active)setError('Chưa lưu lên dữ liệu dùng chung: '+error.message)}).finally(()=>{if(active)setSaving(false)});return()=>{active=false}},[attendance,payslips,ready])
 return {ready,saving,connectionError,retry:()=>refreshRef.current?.(true),importLocal:async(a,p)=>{if(!ready||!stores.current)throw Error('Hãy chờ tải dữ liệu dùng chung.');const rows=await stores.current.a.importMissing(a),slips=await stores.current.p.importMissing(p);setAttendance(rows);setPayslips(slips)}}
}
