import test from 'node:test'
import assert from 'node:assert/strict'
import {decodeEmployee,encodeEmployee,employeeGroup,validateEmployment,storeDocument,readDocument} from '../src/lib/employee-profile.js'
import {employeeExportBuffer} from '../src/lib/employee-export.js'
import {parseEmployeeFile} from '../src/lib/attendance.js'
test('profile roundtrip preserves old salary/schema and employment fields',()=>{const old={id:'a',name:'A',salary:{transfer:123,teacher:{class:45}}};assert.equal(decodeEmployee(old).resigned,false);const emp={...old,email:'a@example.com',startDate:'2025-01-01',endDate:'2026-01-01',resigned:true,documents:[{id:'x',kind:'leaving',storage:'supabase',path:'a/x'}]};const encoded=encodeEmployee(emp);assert(!('email' in encoded));assert.equal(encoded.salary.transfer,123);assert.deepEqual(decodeEmployee(encoded).documents,emp.documents);assert.equal(decodeEmployee(encoded).email,emp.email);assert.equal(employeeGroup([old,emp],true).length,1);assert.equal(employeeGroup([old,emp],false).length,1)})
test('employment validation and Excel roundtrip include email dates and resigned state',async()=>{assert(validateEmployment({email:'bad'}));assert(validateEmployment({startDate:'2026-02-01',endDate:'2026-01-01'}));const e={name:'Test',email:'a@example.com',startDate:'2025-01-01',endDate:'2026-02-02',resigned:true,salary:{}};const buffer=await employeeExportBuffer([e]);const parsed=await parseEmployeeFile({arrayBuffer:async()=>buffer});assert.equal(parsed[0].email,e.email);assert.equal(parsed[0].startDate,e.startDate);assert.equal(parsed[0].endDate,e.endDate);assert.equal(parsed[0].resigned,true)})
test('shared files can be uploaded by one anonymous client and downloaded by another',async()=>{const files=new Map();const client=(user)=>({auth:{getSession:async()=>({data:{session:user?{user}:null}})},storage:{from:bucket=>{assert.equal(bucket,'employee-documents');return {upload:async(path,file)=>{files.set(path,file);return {error:null}},download:async path=>({data:files.get(path),error:null})}}}});const blob=new Blob(['employment document'],{type:'text/plain'});Object.defineProperty(blob,'name',{value:'note.txt'});const metadata=await storeDocument(blob,'joining',client(null),'emp');assert.equal(metadata.storage,'supabase');assert(metadata.path.startsWith('emp/'));assert.equal(await (await readDocument(metadata,client(null))).text(),'employment document')})

