import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import ExcelJS from 'exceljs';import X from 'xlsx';import JSZip from 'jszip';
import {parseAttendanceFile,parseAllAttendanceSheets,parseEmployeeFile,buildLegacyEmployeeSampleWorkbookBuffer as buildEmployeeSampleWorkbookBuffer,buildLegacySampleWorkbookBuffer as buildSampleWorkbookBuffer} from '../src/lib/attendance.js';
import {makePayslip,payslipBuffer,exportMany} from '../src/lib/exporter.js';import {previewGrid} from '../src/lib/preview.js';
const file=b=>({arrayBuffer:async()=>b});const template=await fs.readFile('public/payslip-template.xlsx');globalThis.fetch=async (url,{signal}={})=>{signal?.throwIfAborted();return {ok:true,arrayBuffer:async()=>String(url).startsWith('/summary-')?await fs.readFile('public'+url):template}};
const employee={id:'e',name:'Nguyễn Văn A',bank:'VCB',account:'0123456',position:'Giáo viên',branch:'CN1',salary:{teacher:{class:100,assist:40,tutoring:200,assistTutoring:75},office:{full:7000000,part:50000},transfer:5000000,insuranceBase:4000000,mealAllowance:300000,support:100000,bonus:200000,special1:true,special2:true,special3:true}};
const line=(category,className='IELTS - 56% ONL',extra={})=>({id:crypto.randomUUID(),category,className,date:'2026-10-01',period:'2026-10',start:'18:00',end:'19:30',hours:1.5,teacher:employee.name,ta:'',...extra});
async function sheet(e,rows,type,period='2026-10'){const p=makePayslip(e,period,rows);p.displayPeriod=period;const buf=await payslipBuffer(p,e,rows,type);const w=new ExcelJS.Workbook();await w.xlsx.load(buf);return {ws:w.worksheets[0],w,buf,p}}
function total(ws){let result;ws.eachRow(r=>{if(String(r.getCell(2).value||'').includes('CÒN LẠI THỰC NHẬN'))result=r.getCell(8).value});return result}
test('real workbook: five categories, office multiline, fraction and decimal hours',async()=>{const rows=await parseAllAttendanceSheets(file(await fs.readFile('public/sample-attendance-real.xlsx')));assert(rows.some(r=>r.category==='Văn phòng'));assert(rows.some(r=>r.category==='Lớp chung'&&r.hours===1.5));assert(rows.some(r=>r.category==='Phụ đạo'&&r.hours===0.5));assert(rows.every(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date)));});
test('five-sheet sample imports all five separate categories',async()=>{const b=await buildSampleWorkbookBuffer();const rows=await parseAllAttendanceSheets(file(b));assert.equal(new Set(rows.map(r=>r.category)).size,5);assert.equal(rows.length,5)});
test('duration: explicit 0.5 hour and 12 hour values preserved, time fraction converted',async()=>{const w=X.utils.book_new();const rows=[['Ngày','Tên lớp','Giờ bắt đầu','Giờ kết thúc','Số giờ','Tên GV'],['01/10/2026','A','18:00','19:30',0.0625,employee.name],['01/10/2026','B','18:00','18:30',0.5,employee.name],['01/10/2026','C','08:00','20:00',12,employee.name]];X.utils.book_append_sheet(w,X.utils.aoa_to_sheet(rows),'Lớp chung');const out=await parseAttendanceFile(file(X.write(w,{type:'buffer',bookType:'xlsx'})));assert.deepEqual(out.map(r=>r.hours),[1.5,0.5,12])});
test('employee sample: 22 columns, table, comments, leading zero and mechanisms',async()=>{const b=await buildEmployeeSampleWorkbookBuffer();const w=new ExcelJS.Workbook();await w.xlsx.load(b);const s=w.worksheets[0];assert.equal(s.columnCount,22);assert(s.getTable('Employees'));for(let c=1;c<=22;c++){assert(s.getCell(1,c).note);assert.equal(s.getCell(1,c).font.name,'Times New Roman')}const rows=await parseEmployeeFile(file(b));assert.equal(rows[0].account,'0123456789');assert(rows[0].salary.special1&&rows[0].salary.special2&&!rows[0].salary.special3);assert(rows[1].noAttendance)});
test('special priorities and distinct assist tutoring rate, TA conversion',async()=>{for(const [cat,rate] of [['Lớp chung',100],['Phụ đạo',40],['Lớp kèm',200],['Phụ đạo kèm',75]]){const e={...employee,salary:{...employee.salary,office:{},insuranceBase:0}};const {ws}=await sheet(e,[line(cat)],'teacher');assert.equal(total(ws),Math.round(rate*1.5))}const e={...employee,salary:{...employee.salary,office:{},insuranceBase:0,special3:false}};assert.equal(total((await sheet(e,[line('Lớp kèm')],'teacher')).ws),200*0.8*1.5);const plain={...e,salary:{...e.salary,special1:false,special2:false}};assert.equal(total((await sheet(plain,[line('Lớp chung')],'teacher')).ws),150);const ta=line('Lớp chung','A',{teacher:'Other',ta:employee.name});assert.equal(total((await sheet(plain,[ta],'teacher')).ws),60)});
test('MS2 mapping and leap month formula',async()=>{const {ws}=await sheet(employee,[line('Văn phòng','',{employee:employee.name,hours:8,period:'2024-02',date:'2024-02-01'})],'office','2024-02');assert.equal(ws.getCell('A10').value,'Họ tên:');assert.equal(ws.getCell('E10').value,employee.name);assert.equal(ws.getCell('E12').value,29);assert.equal(ws.getCell('E20').value,7000000);assert.equal(ws.getCell('E21').value,50000);assert.equal(ws.getCell('E26').value,7080000)});
test('MS3 mapping preserves merged labels and formula totals',async()=>{const {ws}=await sheet(employee,[],'transfer');assert.equal(ws.getCell('A9').value,'Họ tên:');assert.equal(ws.getCell('E9').value,employee.name);assert.equal(ws.getCell('E12').value,employee.account);assert.equal(ws.getCell('E17').value,5500000);assert.equal(ws.getCell('E22').value,525000);assert.equal(ws.getCell('E23').value,4975000)});
test('all MS files value-only, correct tab, preview contains values',async()=>{const rows=[line('Lớp chung'),line('Phụ đạo kèm'),line('Văn phòng','',{employee:employee.name,hours:8})];for(const [type,name] of [['teacher','GV'],['office','VP'],['transfer','CK'],['teacherBH','GV_BH'],['officeBH','VP_BH']]){const {w,ws,buf}=await sheet(employee,rows,type);assert.equal(w.worksheets.length,1);assert.equal(ws.name,name);ws.eachRow(r=>r.eachCell(c=>assert.notEqual(c.type,ExcelJS.ValueType.Formula)));const g=await previewGrid(buf,name);assert(g[name].cells.flat().some(c=>c.value===employee.name));assert(g[name].rowCount>10)}});
test('MS4/MS5 revised formulas and net-transfer cash split',async()=>{const rows=[line('Lớp chung'),line('Văn phòng','',{employee:employee.name,hours:8})];const a=(await sheet(employee,rows,'teacherBH')).ws;assert.equal(a.getCell('AG5').value,420000);assert.equal(a.getCell('AK5').value,4980000);assert.equal(a.getCell('Q8').value,total(a)-a.getCell('AK5').value);const b=(await sheet(employee,rows,'officeBH')).ws;assert.equal(b.getCell('AD5').value,420000);assert.equal(b.getCell('AH5').value,4980000);assert.equal(b.getCell('N8').value,b.getCell('E26').value-b.getCell('AH5').value)});
test('detail overflow keeps all rows and totals',async()=>{const e={...employee,salary:{...employee.salary,office:{},insuranceBase:0}};const rows=Array.from({length:14},()=>line('Lớp chung','A'));const {ws}=await sheet(e,rows,'teacher');assert.equal(total(ws),2100);let sum;ws.eachRow(r=>{if(r.getCell(2).value==='TỔNG (1)')sum=r.getCell(6).value});assert.equal(sum,21)});
test('legacy employee and noAttendance do not create synthetic attendance',async()=>{const e={id:'old',name:'Old',salary:{office:{full:100}}};const p=makePayslip(e,'2026-10',[]);assert.deepEqual(p.types,['office']);assert.equal(p.lineEdits.length,0);await payslipBuffer(p,e,[],'office');const q=makePayslip({...employee,noAttendance:true},'2026-10',[]);assert.equal(q.lineEdits.length,0)});
test('abort rejects before template loading',async()=>{const c=new AbortController();c.abort();await assert.rejects(payslipBuffer(makePayslip(employee,'2026-10',[]),employee,[],'office',{signal:c.signal}),{name:'AbortError'})});
test('bulk ZIP keeps one sheet per file, sanitized names and duplicate filenames',async()=>{const rows=[line('Lớp chung')];const p=makePayslip(employee,'2026-10',rows);p.displayPeriod='2026-10';let blob;const oldURL=URL.createObjectURL;URL.createObjectURL=b=>{blob=b;return 'blob:test'};globalThis.document={createElement:()=>({click(){}})};try{await exportMany([p,{...p,id:'other'}],[employee],rows,'PAYSLIP');const z=await JSZip.loadAsync(await blob.arrayBuffer());const files=Object.keys(z.files).filter(n=>!z.files[n].dir&&n.split('/').at(-1).startsWith('PAYSLIP_'));assert.equal(files.length,12);assert(files.every(n=>/^PAYSLIP_CN1_(GIÁO VIÊN|VĂN PHÒNG)\/Nguyễn Văn A\//.test(n)&&/^PAYSLIP_Nguyễn Văn A_(?:(?:GV|VP)_)?CN1_MS[1-5]_/.test(n.split('/').at(-1))));for(const name of files){const w=new ExcelJS.Workbook();await w.xlsx.load(await z.file(name).async('nodebuffer'));assert.equal(w.worksheets.length,1)}}finally{URL.createObjectURL=oldURL;delete globalThis.document}});
test('unknown sheet is not guessed by position',async()=>{const w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([['Ngày','Tên lớp','Tên GV','Tổng giờ'],['01/10/2026','A',employee.name,1]]),'Không rõ');await assert.rejects(parseAllAttendanceSheets(file(X.write(w,{type:'buffer',bookType:'xlsx'}))),/không tìm thấy sheet/)});
import {employeeExportBuffer} from '../src/lib/employee-export.js';
import {SaxesParser} from 'saxes';
async function checkXml(buffer){const zip=await JSZip.loadAsync(buffer,{checkCRC32:true});let count=0;for(const [name,entry] of Object.entries(zip.files)){if(!/\.(xml|rels|vml)$/.test(name))continue;const xml=await entry.async('string');const parser=new SaxesParser({xmlns:true});parser.write(xml).close();count++;if(/^xl\/worksheets\/sheet\d+\.xml$/.test(name)){const legacy=xml.indexOf('<legacyDrawing '),tables=xml.indexOf('<tableParts '),ext=xml.indexOf('<extLst');if(legacy>=0&&tables>=0)assert(legacy<tables,name+' notes before tableParts');if(legacy>=0&&ext>=0)assert(legacy<ext,name+' notes before extLst')}}return count}
test('Excel XML: table and notes order, employee exports populated and empty',async()=>{for(const b of [await buildSampleWorkbookBuffer(),await buildEmployeeSampleWorkbookBuffer(),await employeeExportBuffer([employee]),await employeeExportBuffer([])])assert(await checkXml(b)>5);const b=await employeeExportBuffer([employee]);const w=new ExcelJS.Workbook();await w.xlsx.load(b);const s=w.worksheets[0];assert(s.getTable('EmployeeExport'));assert.equal(s.getCell('F2').value,employee.account);assert(s.getCell('R1').note);assert.equal(s.columnCount,22)});
test('Excel XML: all five payslip types, notes, merges, value-only',async()=>{for(const type of ['teacher','office','transfer','teacherBH','officeBH']){const {buf}=await sheet(employee,[line('Lớp chung')],type);assert(await checkXml(buf)>5)}});
test('MS4/MS5 principal uses transfer; cash subtracts revised local net, not MS3',async()=>{const e={...employee,salary:{...employee.salary,transfer:6000000,insuranceBase:3000000,mealAllowance:200000,support:50000}};for(const type of ['teacherBH','officeBH']){const {ws}=await sheet(e,[],type);if(type==='teacherBH'){assert.equal(ws.getCell('P5').value,6000000);assert.equal(ws.getCell('AK5').value,5935000);assert.equal(ws.getCell('Q7').value,5935000);assert.equal(ws.getCell('Q8').value,total(ws)-5935000)}else{assert.equal(ws.getCell('M5').value,6000000);assert.equal(ws.getCell('AH5').value,5935000);assert.equal(ws.getCell('N7').value,5935000);assert.equal(ws.getCell('N8').value,ws.getCell('E26').value-5935000)}}});
import {toggleVisibleSelection,choiceParts,choiceValue} from '../src/lib/employee-controls.js';
test('selection toggles only visible rows, preserves unrelated IDs, no duplicate',()=>{assert.deepEqual(toggleVisibleSelection(['hidden'],['a','b']),['hidden','a','b']);assert.deepEqual(toggleVisibleSelection(['hidden','a','b'],['a','b']),['hidden']);assert.deepEqual(toggleVisibleSelection(['a'],['a','b']),['a','b']);assert.deepEqual(toggleVisibleSelection(['a'],[]),['a'])});
test('branch/position selections preserve legacy/custom values without schema changes',()=>{assert.deepEqual(choiceParts('TP; PN; Bình Thạnh',['TP','PN']),{selected:['TP','PN'],other:'Bình Thạnh'});assert.deepEqual(choiceParts('Giáo viên',['GV','VP']),{selected:[],other:'Giáo viên'});assert.equal(choiceValue(['GV','VP'],'Điều phối'),'GV; VP; Điều phối');assert.equal(choiceValue([],''),'')});
test('employee header notes multiline TNR and VML hover geometry survive export',async()=>{const b=await buildEmployeeSampleWorkbookBuffer(),z=await JSZip.loadAsync(b);const comments=await z.file('xl/comments1.xml').async('string');assert(comments.includes('Times New Roman'));assert(comments.includes('&#10;')||comments.includes('\n'));const vml=await z.file(Object.keys(z.files).find(n=>n.endsWith('.vml'))).async('string');assert(vml.includes('width:270pt;height:160pt'));assert(vml.includes('ObjectType="Note"'));assert(vml.includes('visibility:hidden'));const w=new ExcelJS.Workbook();await w.xlsx.load(b);for(let c=1;c<=22;c++){const note=w.worksheets[0].getCell(1,c).note;assert(note.texts.length>=2);assert(note.texts.every(t=>t.font.name==='Times New Roman'))}});
import {buildPayslipZip} from '../src/lib/exporter.js';
test('GV and GV_BH insurance occupies lower detail row after resize, total subtracts it',async()=>{for(const count of [0,1,14])for(const type of ['teacher','teacherBH']){const e={...employee,salary:{...employee.salary,office:{},insuranceBase:6200000}};const rows=Array.from({length:count},()=>line('Lớp chung','A'));const {ws}=await sheet(e,rows,type);let heading,detail;ws.eachRow(r=>{if(String(r.getCell(2).value||'').includes('TIỀN BẢO HIỂM TRỪ'))heading=r.number;if(String(r.getCell(1).value||'').includes('BHXH + BHYT + BHTN'))detail=r.number});assert.equal(detail,heading+1);assert.equal(ws.getCell('D'+heading).value,'');assert.equal(ws.getCell('D'+detail).value,651000);assert.equal(total(ws),count*150-651000)}});
test('export branch folders with single-file and multi-template personal folders',async()=>{const a={...employee,id:'a',name:'A',branch:'TP'},b={...employee,id:'b',name:'B',branch:'TP'},c={...employee,id:'c',name:'C',branch:'PN'};const ps=[a,b,c].map(e=>({...makePayslip(e,'2026-10',[]),displayPeriod:'2026-10'}));ps[0].types=['teacher'];ps[1].types=['office','transfer','officeBH'];ps[2].types=['teacher','teacherBH'];const z=await buildPayslipZip(ps,[a,b,c],[]);const files=Object.keys(z.files).filter(n=>!z.files[n].dir);assert.equal(files.length,6);assert(files.some(n=>n==='PAYSLIP_TÂN PHÚ_GIÁO VIÊN/PAYSLIP_A_GV_TP_MS1_2026-10.xlsx'));assert.equal(files.filter(n=>n.startsWith('PAYSLIP_TÂN PHÚ_VĂN PHÒNG/B/')).length,3);assert.equal(files.filter(n=>n.startsWith('PAYSLIP_PHÚ NHUẬN_GIÁO VIÊN/C/')).length,2);for(const name of files){const w=new ExcelJS.Workbook();await w.xlsx.load(await z.file(name).async('nodebuffer'));assert.equal(w.worksheets.length,1)}});
test('employee import maps exact branch/position picks or custom text',async()=>{const w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([['Họ và tên','Chi nhánh','Chức vụ'],['A','TP','GV'],['B','PN','VP'],['C','Bình Thạnh','Điều phối']]),'NV');const rows=await parseEmployeeFile(file(X.write(w,{type:'buffer',bookType:'xlsx'})));assert.deepEqual(choiceParts(rows[0].branch,['TP','PN']),{selected:['TP'],other:''});assert.deepEqual(choiceParts(rows[1].position,['GV','VP']),{selected:['VP'],other:''});assert.equal(choiceParts(rows[2].branch,['TP','PN']).other,'Bình Thạnh');assert.equal(choiceParts(rows[2].position,['GV','VP']).other,'Điều phối')});
test('employee guidance covers input columns, notes are anchored beside each sample cell',async()=>{const b=await buildEmployeeSampleWorkbookBuffer(),w=new ExcelJS.Workbook();await w.xlsx.load(b);const s=w.worksheets[0];for(let c=1;c<=22;c++){assert(s.getCell(2,c).note);assert(s.getCell(3,c).note);const v=s.getCell(100,c).dataValidation;assert(v.showInputMessage);assert(v.prompt.length<=255)}const z=await JSZip.loadAsync(b);const vml=await z.file(Object.keys(z.files).find(n=>n.endsWith('.vml'))).async('string');assert(vml.includes('<x:Anchor>1, 6, 1, 2, 5, 10, 10, 10</x:Anchor>'));assert(await checkXml(b)>5)});
test('period cells in all five exports align left and preview year has no thousands separator',async()=>{const rows=[line('Lớp chung'),line('Văn phòng','',{employee:employee.name,hours:8})];for(const type of ['teacher','office','transfer','teacherBH','officeBH']){const {ws,buf}=await sheet(employee,rows,type);const row=type==='transfer'?6:7;for(const column of ['B','E']){assert.equal(ws.getCell(column+row).numFmt,'0');assert.equal(ws.getCell(column+row).alignment.horizontal,'left')}const grid=(await previewGrid(buf,ws.name))[ws.name];const year=grid.cells.flat().find(c=>c.r===row&&c.c===5);assert.equal(String(year.value),'2026')}})
test('export role names follow each template; MS3 omits role for mixed GV/TG/VP/custom positions',async()=>{const e={...employee,position:'GV; TG; VP; Điều phối',branch:'TP'};const rows=[line('Lớp chung'),line('Văn phòng','',{employee:e.name,hours:8})];const p=makePayslip(e,'2026-10',rows);p.displayPeriod='2026-10';p.types=['teacher','office','transfer','teacherBH','officeBH'];const zip=await buildPayslipZip([p],[e],rows);const files=Object.keys(zip.files).filter(n=>n.endsWith('.xlsx'));assert.equal(files.length,6);for(const [code,role] of [['MS1','GV'],['MS2','VP'],['MS4','GV'],['MS5','VP']])assert(files.some(n=>n.endsWith(`_${role}_TP_${code}_2026-10.xlsx`)));const cks=files.filter(n=>n.includes('_MS3_'));assert.equal(cks.length,2);assert(cks.some(n=>n.startsWith('PAYSLIP_TÂN PHÚ_GIÁO VIÊN/')));assert(cks.some(n=>n.startsWith('PAYSLIP_TÂN PHÚ_VĂN PHÒNG/')));const ck=cks[0];assert(ck.endsWith(`PAYSLIP_${e.name}_TP_MS3_2026-10.xlsx`));assert(files.every(n=>!n.includes('Điều phối')&&!n.includes('_TG_')&&!n.includes('GV;')))})

test('blank branch is omitted from filename while archive retains unassigned folder',async()=>{const e={...employee,branch:'  ',position:'TG'};const p={...makePayslip(e,'2026-10',[]),displayPeriod:'2026-10',types:['teacher','transfer']};const zip=await buildPayslipZip([p],[e],[]);const names=Object.keys(zip.files).filter(n=>n.endsWith('.xlsx'));assert.equal(names.length,2);assert(names.some(n=>n.endsWith('PAYSLIP_'+e.name+'_GV_MS1_2026-10.xlsx')));assert(names.some(n=>n.endsWith('PAYSLIP_'+e.name+'_MS3_2026-10.xlsx')));assert(names.every(n=>!n.split('/').at(-1).includes('UNKNOWN')&&!n.split('/').at(-1).includes('Chưa có chi nhánh')))})


test('revised MS4/MS5 use employee insurance base and progressive tax across brackets',async()=>{
 const tax=x=>{let result=0;for(const [width,rate] of [[10000000,.05],[20000000,.1],[30000000,.2],[40000000,.3],[Infinity,.35]]){const part=Math.min(Math.max(x,0),width);result+=part*rate;x-=part}return result};
 for(const transfer of [9000000,20000000,40000000,80000000,150000000])for(const type of ['teacherBH','officeBH']){
  const base=6000000,e={...employee,salary:{...employee.salary,transfer,insuranceBase:base,mealAllowance:300000,support:100000}};
  const {ws}=await sheet(e,[],type),teacher=type==='teacherBH',insurance=base*.105,expectedTax=tax(Math.max(transfer-15500000-insurance,0));
  assert.equal(ws.getCell(teacher?'V5':'S5').value,base);
  assert.equal(ws.getCell(teacher?'R5':'O5').value,0);
  assert.equal(ws.getCell(teacher?'AI5':'AF5').value,expectedTax);
  assert.equal(ws.getCell(teacher?'AK5':'AH5').value,transfer+400000-insurance-expectedTax);
  assert.match(String(ws.getCell(teacher?'R1':'O1').value),/13/);
 }
});

test('office department is VP for mixed-role employees in export and preview',async()=>{for(const type of ['office','officeBH']){const {ws,buf}=await sheet({...employee,position:'GV; VP'},[],type);assert.equal(ws.getCell('E11').value,'VP');const grid=(await previewGrid(buf,ws.name))[ws.name];assert.equal(grid.cells.flat().find(c=>c.r===11&&c.c===5).value,'VP')}});

test('GV and GV_BH require teaching attendance in the selected period, including noAttendance employees',()=>{
 for(const noAttendance of [false,true]){
  const e={...employee,noAttendance};
  for(const rows of [[],[line('Văn phòng','',{employee:e.name})],[line('Lớp chung','',{period:'2026-09'})],[line('Lớp chung','',{teacher:'Other',ta:''})]]){
   const p=makePayslip(e,'2026-10',rows);assert(!p.types.includes('teacher'));assert(!p.types.includes('teacherBH'));assert(p.types.includes('transfer'));assert(p.types.includes('office'));
  }
  for(const category of ['Lớp chung','Phụ đạo','Lớp kèm','Phụ đạo kèm']){
   const p=makePayslip(e,'2026-10',[line(category)]);assert(p.types.includes('teacher'));assert(p.types.includes('teacherBH'));
  }
 }
});

test('empty or invalid teaching rows do not generate GV templates',()=>{for(const extra of [{hours:0},{date:''},{className:''}]){const p=makePayslip(employee,'2026-10',[line('Lớp chung','A',extra)]);assert(!p.types.includes('teacher'));assert(!p.types.includes('teacherBH'))}});

test('mechanism 4: common percent classes use 170k, no stacking; other categories and legacy preserved',async()=>{const e={...employee,salary:{...employee.salary,insuranceBase:0,office:{},special1:true,special2:true,special3:false,special4:true}};assert.equal(total((await sheet(e,[line('Lớp chung','A 50% ONL')],'teacher')).ws),255000);assert.equal(total((await sheet(e,[line('Lớp chung','A')],'teacher')).ws),150);assert.equal(total((await sheet(e,[line('Phụ đạo','A 50%')],'teacher')).ws),48);assert.equal(total((await sheet(e,[line('Lớp kèm','A 50% ONL')],'teacher')).ws),240);const ta=line('Lớp chung','A 50%',{teacher:'Other',ta:e.name});assert.equal(total((await sheet(e,[ta],'teacher')).ws),48);const b=await employeeExportBuffer([e]);assert((await parseEmployeeFile(file(b)))[0].salary.special4);const w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([['Họ tên','Cơ chế 4'],['A',1]]),'NV');assert((await parseEmployeeFile(file(X.write(w,{type:'buffer',bookType:'xlsx'}))))[0].salary.special4)});

test('mechanism 4 wins over 3 for common IELTS 56% ONL; disabled 4 preserves 3',async()=>{for(const special4 of [true,false]){const e={...employee,salary:{...employee.salary,office:{},insuranceBase:0,special3:true,special4}};assert.equal(total((await sheet(e,[line('Lớp chung')],'teacher')).ws),special4?255000:150)}});
