import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import ExcelJS from 'exceljs';import JSZip from 'jszip';import X from 'xlsx';import {parseAllAttendanceSheets,parseAttendanceFile,parseEmployeeFile} from '../src/lib/attendance.js';import {makePayslip,payslipBuffer} from '../src/lib/exporter.js';import {decodeEmployee} from '../src/lib/employee-profile.js';
const input=b=>({arrayBuffer:async()=>b});const template=await fs.readFile('public/payslip-template.xlsx');globalThis.fetch=async()=>({ok:true,arrayBuffer:async()=>template});
const e={id:'a',name:'Test GV',salary:{teacher:{class:100000,assist:50000,tutoring:200000,assistTutoring:30000},office:{},insuranceBase:6000000,transfer:5000000}};
const row=(i,amount)=>({id:String(i),category:'Placement Test',date:'2026-10-01',period:'2026-10',teacher:e.name,student:'Học viên '+i,...(amount===undefined?{}:{amount})});
async function exported(rows,type='teacher'){const wb=new ExcelJS.Workbook();await wb.xlsx.load(await payslipBuffer(makePayslip(e,'2026-10',rows),e,rows,type));return wb.worksheets[0]}
function findTotal(ws){let value;ws.eachRow(r=>{if(String(r.getCell(2).value||'').includes('CÒN LẠI THỰC NHẬN'))value=r.getCell(8).value});return value}
test('supplied import assets contain at most two data rows and new headers/six tabs',async()=>{for(const name of ['MAU_IMPORT_NHAN_VIEN.xlsx','MAU_IMPORT_CHAM_CONG.xlsx']){const bytes=await fs.readFile('public/'+name),w=new ExcelJS.Workbook();await w.xlsx.load(bytes);for(const s of w.worksheets){s.eachRow(r=>{if(r.number>3)r.eachCell(c=>assert(c.value==null,'unexpected example record '+c.address))})}if(name.includes('NHAN')){assert.deepEqual(w.worksheets[0].getRow(1).values.slice(1,7),['Họ và tên','Chi nhánh','Chức vụ','Email','Ngân hàng','STK']);assert.equal((await parseEmployeeFile(input(bytes))).length,2)}else{assert.equal(w.worksheets.length,6);const rows=await parseAllAttendanceSheets(input(bytes));assert(rows.some(r=>r.category==='Placement Test'));assert(rows.filter(r=>r.category==='Placement Test').every(r=>r.amount===20000))}assert(await JSZip.loadAsync(bytes,{checkCRC32:true}))}});
test('Placement Test parser preserves money, blank default, explicit zero and student',async()=>{const w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([['Ngày','Thứ','Tên HV','PLACEMENT TEST','Tên GV'],['01/10/2026','','A','',e.name],['01/10/2026','','B',35000,e.name],['01/10/2026','','C',0,e.name]]),'Placement Test');const rows=await parseAttendanceFile(input(X.write(w,{type:'buffer',bookType:'xlsx'})),'Placement Test','Placement Test');assert.deepEqual(rows.map(r=>r.amount),[20000,35000,0]);assert.deepEqual(rows.map(r=>r.student),['A','B','C'])});
test('Placement-only creates GV/GV_BH and all placement rows survive resize',async()=>{for(const count of [1,4,14]){const rows=Array.from({length:count},(_,i)=>row(i));const p=makePayslip(e,'2026-10',rows);assert(p.types.includes('teacher'));assert(p.types.includes('teacherBH'));for(const type of ['teacher','teacherBH']){const ws=await exported(rows,type);assert.equal(findTotal(ws),count*20000-630000);assert.equal(ws.getCell('D16').value,20000);for(let i=0;i<count;i++){let found=false;ws.eachRow(r=>{if(r.getCell(3).value==='Học viên '+i){assert.equal(r.getCell(8).value,20000);found=true}});assert(found)}if(type==='teacherBH')assert.equal(ws.getCell('Q8').value,findTotal(ws)-ws.getCell('Q7').value)}}});
test('new GV totals include tutoring, placement, other categories and lower insurance after shifting',async()=>{const teaching=['Lớp chung','Phụ đạo','Lớp kèm','Phụ đạo kèm'].map((category,i)=>({id:'t'+i,category,date:'2026-10-01',period:'2026-10',teacher:e.name,className:'A',hours:1,start:'18:00',end:'19:00'}));const ws=await exported([...teaching,row(0,35000),row(1,0)]);assert.equal(findTotal(ws),100000+50000+200000+30000+35000-630000);ws.eachRow(r=>r.eachCell(c=>assert.notEqual(c.type,ExcelJS.ValueType.Formula)))});
test('mechanisms 3/4 reject conflicting import; old stored pair normalizes to single selection',async()=>{const w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([['Họ tên','Cơ chế lương đặc biệt'],['A','3; 4']]),'NV');await assert.rejects(parseEmployeeFile(input(X.write(w,{type:'buffer',bookType:'xlsx'}))),/chỉ được chọn một/);const decoded=decodeEmployee({...e,salary:{...e.salary,special3:true,special4:true}});assert(decoded.salary.special4);assert(!decoded.salary.special3)});
