import test from 'node:test';import assert from 'node:assert/strict';import {SharedCollection} from '../src/lib/shared-payroll.js';
function client(){const rows=new Map();let fail=false;return {rows,setFail(v){fail=v},from(){return {upsert:async row=>{if(fail)return {error:Error('offline')};for(const item of (Array.isArray(row)?row:[row]))rows.set(item.id,structuredClone(item));return {}},delete(){return {in:async(_,ids)=>{if(fail)return {error:Error('offline')};for(const id of ids)rows.delete(id);return {}}}},select(){return {order(){return {range:async(a,b)=>({data:[...rows.values()].sort((a,b)=>a.id.localeCompare(b.id)).slice(a,b+1)})}}}}}}}}
test('two devices preserve independent additions and explicit deletions',async()=>{const c=client(),a=new SharedCollection(c,'test'),b=new SharedCollection(c,'test');await a.load();await b.load();a.edit([{id:'a',hours:1}]);b.edit([{id:'b',hours:2}]);await Promise.all([a.flush(),b.flush()]);assert.equal(c.rows.size,2);const all=await a.load();a.edit(all.filter(x=>x.id!=='a'));await a.flush();assert.equal(c.rows.size,1);assert.equal((await b.load())[0].id,'b')});
test('failed saves retry without losing pending data; migration keeps cloud values',async()=>{const c=client(),a=new SharedCollection(c,'test');await a.load();a.edit([{id:'a',hours:2}]);c.setFail(true);await assert.rejects(a.flush(),/offline/);assert.equal(a.pending.size,1);c.setFail(false);await a.flush(true);assert.equal(a.pending.size,0);const out=await a.importMissing([{id:'a',hours:99},{id:'b',hours:3}]);assert.equal(out.find(x=>x.id==='a').hours,2);assert.equal(out.length,2)});
test('shared reads paginate beyond server row limit',async()=>{const c=client();for(let i=0;i<1201;i++)c.rows.set(String(i),{id:String(i),data:{id:String(i)}});assert.equal((await new SharedCollection(c,'test').load()).length,1201)});

test('bulk upload uses bounded batches and acknowledges only successful batches',async()=>{const sent=[];let failAt=2;const c={from(){return {upsert:async rows=>{sent.push(rows);return sent.length===failAt?{error:Error('timeout')}:{}}}}};const store=new SharedCollection(c,'test');store.edit(Array.from({length:123},(_,i)=>({id:String(i),hours:i})));await assert.rejects(store.flush(),/timeout/);assert.equal(store.pending.size,73);assert.deepEqual(sent.map(r=>r.length),[50,50]);failAt=0;await store.flush(true);assert.equal(store.pending.size,0);assert.deepEqual(sent.map(r=>r.length),[50,50,50,23])});
test('concurrent flush shares one request and preserves edits made during upload',async()=>{let release;const sent=[];const c={from(){return {upsert:async rows=>{sent.push(rows);if(sent.length===1)await new Promise(r=>release=r);return {}}}}};const store=new SharedCollection(c,'test');store.edit([{id:'a',hours:1}]);const first=store.flush();assert.equal(store.flush(),first);store.edit([{id:'a',hours:2}]);release();await first;assert.equal(sent.length,2);assert.equal(sent[1][0].data.hours,2);assert.equal(store.pending.size,0)});

test('timeouts back off automatic retries while manual retry bypasses the wait',async()=>{let calls=0,fail=true;const c={from(){return {upsert:async()=>{calls++;return fail?{error:Error('timeout')}:{}}}}};const store=new SharedCollection(c,'test');store.edit([{id:'a'}]);await assert.rejects(store.flush(),/timeout/);await assert.rejects(store.flush(),/timeout/);assert.equal(calls,1);assert.equal(store.pending.size,1);fail=false;await store.flush(true);assert.equal(calls,2);assert.equal(store.pending.size,0)});

test('stale cloud read cannot replace baseline of a payslip created during refresh',async()=>{let release;const c={from(){return {select(){return {order(){return {range:async()=>{await new Promise(r=>release=r);return {data:[]}}}}}},upsert:async()=>({})}}};const store=new SharedCollection(c,'test');store.accept([]);const revision=store.revision;const reading=store.load();store.edit([{id:'new-payslip',employeeName:'A'}]);await store.flush();release();await reading;assert.notEqual(store.revision,revision);assert(store.shown.has('new-payslip'));store.edit([{id:'new-payslip',employeeName:'A'}]);assert.equal(store.pending.size,0)});
