import {useState} from 'react';
const blank=()=>({detail:'',time:'',days:'',note:''});
export function LeaveDetailModal({rows,values,close,confirm}){
 const [person,setPerson]=useState(rows[0].id),[details,setDetails]=useState(()=>Object.fromEntries(rows.map(r=>[r.id,[blank(),blank(),blank()]]))),[error,setError]=useState('');
 const update=(i,k,v)=>setDetails(prev=>({...prev,[person]:prev[person].map((r,n)=>n===i?{...r,[k]:v}:r)}));
 function done(){for(const entries of Object.values(details))for(const r of entries)if(r.days!==''&&(!Number.isFinite(Number(r.days))||Number(r.days)<0)){setError('Số ngày chi tiết phải là số không âm.');return}confirm(Object.fromEntries(Object.entries(details).map(([id,entries])=>[id,entries.filter(r=>Object.values(r).some(v=>String(v).trim()!=='')).map(r=>({...r,days:r.days===''?'':Number(r.days)}))])))}
 const counts=values[person];
 return <div className="modal-backdrop import-review-backdrop"><div className="modal leave-modal"><div className="modal-head"><div><span className="modal-kicker">BỔ SUNG NGÀY NGHỈ · CHI TIẾT</span><h3>Chi tiết ngày nghỉ</h3><p className="muted">Có thể để trống chi tiết. Dữ liệu được giữ khi đổi nhân viên.</p></div><button className="modal-close" onClick={close}>×</button></div><div className="leave-body"><label>Nhân viên<select aria-label="Chọn nhân viên khai báo nghỉ" value={person} onChange={e=>setPerson(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><p className="muted">Nghỉ bù: {counts.compensatory} · Nghỉ phép: {counts.paid} · Nghỉ không phép: {counts.unpaid}</p><div className="leave-table-wrap"><table className="leave-table"><thead><tr><th>Chi tiết</th><th>Thời gian</th><th>Số ngày</th><th>Ghi chú</th></tr></thead><tbody>{details[person].map((r,i)=><tr key={i}>{['detail','time','days','note'].map((k,c)=><td key={k}><input placeholder="Dữ liệu trống" aria-label={['Chi tiết','Thời gian','Số ngày','Ghi chú'][c]+' dòng '+(i+1)} type={k==='days'?'number':'text'} min={k==='days'?0:undefined} step={k==='days'?0.5:undefined} value={r[k]} onChange={e=>update(i,k,e.target.value)}/></td>)}</tr>)}</tbody></table></div><button className="secondary" onClick={()=>setDetails(d=>({...d,[person]:[...d[person],blank()]}))}>+ Thêm dòng</button>{error&&<p role="alert">{error}</p>}</div><div className="modal-foot"><button className="secondary" onClick={close}>Quay lại</button><button className="secondary" disabled={rows.findIndex(r=>r.id===person)===rows.length-1} onClick={()=>setPerson(rows[rows.findIndex(r=>r.id===person)+1].id)}>Nhân viên tiếp theo</button><button className="primary" onClick={done}>Xong</button></div></div></div>
}
export function InsuranceBranchModal({issues,close,confirm}){
 const [selected,setSelected]=useState({}),[error,setError]=useState('');
 function submit(){if(issues.some(x=>selected[x.choiceKey||x.employee.id]===undefined)){setError('Chọn chi nhánh cho từng nhân viên trước khi khởi tạo.');return}confirm(selected)}
 return <div className="modal-backdrop import-review-backdrop insurance-branch-backdrop"><div className="modal leave-modal"><div className="modal-head"><div><h3>Chọn chi nhánh trừ bảo hiểm</h3><p className="muted">Không chi nhánh nào đủ lương. Chọn một nơi nhận toàn bộ khoản trừ; thực nhận ở nơi đó có thể âm.</p></div><button className="modal-close" onClick={close}>×</button></div><div className="leave-body">{issues.map(x=><div className="insurance-choice" key={x.choiceKey||x.employee.id}><b>{x.employee.name}</b><p>Bảo hiểm: {x.amount.toLocaleString('vi-VN')}đ</p><select aria-label={'Chi nhánh trừ BH '+x.employee.name} value={selected[x.choiceKey||x.employee.id]??''} onChange={e=>setSelected(v=>({...v,[x.choiceKey||x.employee.id]:e.target.value}))}><option value="" disabled>Chọn chi nhánh</option>{x.candidates.map(c=><option key={c.branch} value={c.branch}>{c.branch||'Chưa có chi nhánh'} — lương {Math.round(c.gross).toLocaleString('vi-VN')}đ</option>)}</select></div>)}{error&&<p role="alert">{error}</p>}</div><div className="modal-foot"><button className="secondary" onClick={close}>Quay lại</button><button className="primary" onClick={submit}>Xác nhận &amp; khởi tạo</button></div></div></div>
}
